# Generated by Django 5.2 on 2025-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='growth_stage',
            field=models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready to Harvest')], default='planted', max_length=20),
        ),
    ]
