# Generated by Django 5.2 on 2025-04-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_crop_growth_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growth_stage',
            field=models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready to Harvest')], default='planted', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='farm.livestock')),
            ],
        ),
    ]
